version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: file-downloader_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/your-username/umbrel-downloader:latest
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /home/umbrel/umbrel/home/Downloads/movies:/downloads
    environment:
      - TZ=${TZ}
