version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: local-apps-file-downloader_web_1
      APP_PORT: 8080

  web:
    image: file-downloader:latest
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/downloads:/downloads
    environment:
      - TZ=${TZ}
